name: Build and push Docker image to GitHub Container Registry

on:
  push:
    branches: [ main ]

env:
  CR_PAT: ${{ secrets.CR_PAT }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - run: echo "🎉 checked out ${{ github.actor }}/${{ github.repository }}"
#      - name: Build and push the Docker image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          push: true
#          tags: ghcr.io/${{ github.actor }}/${{ github.repository }}:latest
#          username: ${{ github.actor }}
#          password: ${{ secrets.CR_PAT }}
